### ISSUE TITLE
group products per category

### ISSUE THREAD

**Issue by edgaleano** [vokomokum/foodsoft-vokomokum#2]
in the old dry ordering system products are orered by category so that:

1. it's easier to order
2. it's easy to review which products have and have not arrived (in vokomokum they call this the setup list)
3. it's easier to find products on pickup day.

We think foodsoft doesn't allow for the making of these categories. 

In the upload step (see #1), the person doing the upload should be able to:

1. select the category in the preview screen where people can select/unselect a product
2. bulk upload the category linked to a product. a good option is to select the category in the text file for bulk selecting products (desribed in #1)

People ordering the products should be able to see the different categories in the left navigation menu, just like different suppliers are also listed there.

**Comment by wvengen** [comment]
Foodsoft has its own categories that you can manage. You can (and need to) select a category for each imported product (in the case of Odin, this would be importing from the shared database). On synchronisation (to update prices), the category is kept.
This category is used during member ordering. It may also be used during the order process (like printing distribution lists and such), but I can't fully recall that anymore, so you'll have to check.

When batch uploading products, you _might_ be able to pick a category from the spreadsheet (but I'm not fully sure). Batch upload _could_ be used with the shared database (if you make sure the product number is synced), but I would not really recommend that. This would be mostly relevant for the initial setting up, where you could also use other ways (e.g. directly working with the database to batch update the product category).

**Comment by edgaleano** [comment]
@wvengen that's great! I didn't find that functionaty in foodsoft. where can I find the category? when we import a product?

and about the bulk upload: I'll see if we can indeed set this category in the spreadsheet. And if we can't, then we'll just edit the database directly or find some other better way to do this in batch.

> This would be mostly relevant for the initial setting up

So: once the category is set for a product, afterwards (with a bulk upload, or sync from sharedlists) the category is kept?

**Comment by wvengen** [comment]
> So: once the category is set for a product, afterwards (with a bulk upload, or sync from sharedlists) the category is kept?

Yes, read also [Foodsoft's wiki on the Shared database](https://github.com/foodcoops/foodsoft/wiki/Shared-database). Basically, you can import Odin products and assign local changes to the product. Then you can synchronise these products with the shared database (assuming the shared database has received an update), and review all changes. Prices will be recomputed based on the foodcoop-distribution-unit, so basically this should be a relatively simple process.

**Comment by wvengen** [comment]
> where can I find the category? when we import a product?

Yes, if you import a product, you get the 'product edit' modal form, where you can set the product (I think there could also be a function where you choose a category before importing, so you don't need to edit this for multiple products - but I'm not sure if I only added that in the foodcoop-adam fork or not).

**Comment by edgaleano** [comment]
awesome that we can make local changes (like setting the category) and that it then keeps on syncing with odin for price changes :raised_hands: and thanks for the link to the documentation. that's very useful. I've linked to it from #1 

> but I'm not sure if I only added that in the foodcoop-adam fork or not

we'll test it, and if it isn't in the main version we'll add it :+1: 

in conclusion: this functionality already exists, so I'll close the issue!
